### ISSUE TITLE
Issue in activity switching

### ISSUE THREAD

**Issue by surya-ra** [ser515-team-1/KLAPP#1]
The application is not switching to signup activity. It remains frozen at the main activity screen. Something change needs to be done on the manifest file.

**Comment by rohitksingh** [comment]
Gotcha! 
You need to move the <intent-filter> tag inside <signupactivity> tag. in the manifest.xml file

**Comment by rohitksingh** [comment]
<activity
            android:name=".SignupActivity">
            <intent-filter>
                <action android:name="android.intent.action.MAIN" />
                <category android:name="android.intent.category.LAUNCHER" />
            </intent-filter>
        </activity>

**Comment by rohitksingh** [comment]
Gotcha! you need to declare the SignupActivity as the launcher activity. Since right now the MainActivity is the launcher activity by default. 
You can make your activity as the launcher activity by defining the intent-filter tag inside activity tag in Manifest.xml file.
Change it, test it and revert back to original so that it does not give merge conflicts. 
I have tested your code it works just fine

**Comment by rohitksingh** [comment]
<?xml version="1.0" encoding="utf-8"?>
    <manifest xmlns:android="http://schemas.android.com/apk/res/android"
        package="com.asu.ser.klapp">
        <application
           android:allowBackup="true"
           android:icon="@mipmap/ic_launcher"
           android:label="@string/app_name"
           android:roundIcon="@mipmap/ic_launcher_round"
           android:supportsRtl="true"
           android:theme="@style/AppTheme">
           <activity
               android:name=".MainActivity"
               android:label="@string/app_name">
           </activity>
           <activity android:name=".SignupActivity">
               <intent-filter>
                 <action android:name="android.intent.action.MAIN" />
                 <category android:name="android.intent.category.LAUNCHER" />
               </intent-filter>
           </activity>
       </application>
    </manifest>

Use this for testing

**Comment by surya-ra** [comment]
Awesome! This worked fine. Thank you.

**Comment by surya-ra** [comment]
I will close the issue.
