### ISSUE TITLE
Some .gitignore files made it through in some branches

### ISSUE THREAD

**Issue by rohitksingh** [ser515-team-1/KLAPP#9]
<img width="1440" alt="Screenshot 2019-10-09 at 6 12 12 PM" src="https://user-images.githubusercontent.com/11274840/66531440-a4bd4a80-eac0-11e9-9020-a5c62a0c8c06.png">
Please compare your branch with master branch. Remove the unnecessary files before the integration of all branches.

**Comment by khushboogithub** [comment]
Removed .idea files and build files
